language: java
jdk:
  - openjdk11

branches:
  only:
    - master

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

notifications:
  email:
    recipients:
      - jeaha1217@gmail.com 